export const MODAL_TYPE_ADD_PROJECT = 'MODAL_TYPE_ADD_PROJECT';
export const MODAL_TYPE_ADD_NEW_USER = 'MODAL_TYPE_ADD_NEW_USER';
export const MODAL_TYPE_ADD_NEW_STORY = 'MODAL_TYPE_ADD_NEW_STORY';

